# -*- coding: utf-8 -*-
## File autogenerated by SQLAutoCode
## see http://code.google.com/p/sqlautocode/

from sqlalchemy import *
from sqlalchemy.dialects.mysql import *

metadata = MetaData()


tArray = Table('tArray', metadata,*[
    Column('data_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('arr_data', BLOB(), primary_key=False, nullable=False),])


tArray_aud = Table('tArray_aud', metadata,*[
    Column('data_id', INTEGER(display_width=11), primary_key=False),
    Column('arr_data', BLOB(), primary_key=False),
    Column('action', VARCHAR(length=12), primary_key=False),
    Column('aud_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('aud_time', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),])


tAttr = Table('tAttr', metadata,*[
    Column('attr_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('attr_name', VARCHAR(length=45), primary_key=False, nullable=False),
    Column('attr_dimen', VARCHAR(length=45), primary_key=False),
    Column('cr_date', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),])
Index('attr_name', tAttr.c.attr_name, tAttr.c.attr_dimen, unique=True)


tAttrMap = Table('tAttrMap', metadata,*[
    Column('attr_id_a', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('attr_id_b', INTEGER(display_width=11), primary_key=True, nullable=False),
    ForeignKeyConstraint(['attr_id_b'], [u'hydradb.tAttr.attr_id'], name=u'tAttrMap_ibfk_2'),
    ForeignKeyConstraint(['attr_id_a'], [u'hydradb.tAttr.attr_id'], name=u'tAttrMap_ibfk_1'),])
Index('attr_id_b', tAttrMap.c.attr_id_b, unique=False)


tAttrMap_aud = Table('tAttrMap_aud', metadata,*[
    Column('attr_id_a', INTEGER(display_width=11), primary_key=False),
    Column('attr_id_b', INTEGER(display_width=11), primary_key=False),
    Column('action', VARCHAR(length=12), primary_key=False),
    Column('aud_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('aud_time', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),])


tAttr_aud = Table('tAttr_aud', metadata,*[
    Column('attr_id', INTEGER(display_width=11), primary_key=False),
    Column('attr_name', VARCHAR(length=45), primary_key=False),
    Column('attr_dimen', VARCHAR(length=45), primary_key=False),
    Column('cr_date', TIMESTAMP(), primary_key=False),
    Column('action', VARCHAR(length=12), primary_key=False),
    Column('aud_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('aud_time', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),])


tConstraint = Table('tConstraint', metadata,*[
    Column('constraint_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('scenario_id', INTEGER(display_width=11), primary_key=False, nullable=False),
    Column('group_id', INTEGER(display_width=11), primary_key=False),
    Column('constant', DOUBLE(asdecimal=True), primary_key=False, nullable=False),
    Column('op', VARCHAR(length=10), primary_key=False, nullable=False),
    ForeignKeyConstraint(['scenario_id'], [u'hydradb.tScenario.scenario_id'], name=u'tConstraint_ibfk_1'),])
Index('scenario_id', tConstraint.c.scenario_id, unique=False)


tConstraintGroup = Table('tConstraintGroup', metadata,*[
    Column('group_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('constraint_id', INTEGER(display_width=11), primary_key=False, nullable=False),
    Column('ref_key_1', VARCHAR(length=45), primary_key=False, nullable=False),
    Column('ref_id_1', INTEGER(display_width=11), primary_key=False, nullable=False),
    Column('ref_key_2', VARCHAR(length=45), primary_key=False),
    Column('ref_id_2', INTEGER(display_width=11), primary_key=False),
    Column('op', VARCHAR(length=10), primary_key=False),
    ForeignKeyConstraint(['constraint_id'], [u'hydradb.tConstraint.constraint_id'], name=u'tConstraintGroup_ibfk_1'),])
Index('constraint_id', tConstraintGroup.c.constraint_id, unique=False)


tConstraintGroup_aud = Table('tConstraintGroup_aud', metadata,*[
    Column('group_id', INTEGER(display_width=11), primary_key=False),
    Column('constraint_id', INTEGER(display_width=11), primary_key=False),
    Column('ref_key_1', VARCHAR(length=45), primary_key=False),
    Column('ref_id_1', INTEGER(display_width=11), primary_key=False),
    Column('ref_key_2', VARCHAR(length=45), primary_key=False),
    Column('ref_id_2', INTEGER(display_width=11), primary_key=False),
    Column('op', VARCHAR(length=10), primary_key=False),
    Column('action', VARCHAR(length=12), primary_key=False),
    Column('aud_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('aud_time', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),])


tConstraintItem = Table('tConstraintItem', metadata,*[
    Column('item_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('constraint_id', INTEGER(display_width=11), primary_key=False, nullable=False),
    Column('resource_attr_id', INTEGER(display_width=11), primary_key=False),
    Column('constant', BLOB(), primary_key=False),
    ForeignKeyConstraint(['resource_attr_id'], [u'hydradb.tResourceAttr.resource_attr_id'], name=u'tConstraintItem_ibfk_2'),
    ForeignKeyConstraint(['constraint_id'], [u'hydradb.tConstraint.constraint_id'], name=u'tConstraintItem_ibfk_1'),])
Index('constraint_id', tConstraintItem.c.constraint_id, unique=False)
Index('resource_attr_id', tConstraintItem.c.resource_attr_id, unique=False)


tConstraintItem_aud = Table('tConstraintItem_aud', metadata,*[
    Column('item_id', INTEGER(display_width=11), primary_key=False),
    Column('constraint_id', INTEGER(display_width=11), primary_key=False),
    Column('resource_attr_id', INTEGER(display_width=11), primary_key=False),
    Column('constant', BLOB(), primary_key=False),
    Column('action', VARCHAR(length=12), primary_key=False),
    Column('aud_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('aud_time', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),])


tConstraint_aud = Table('tConstraint_aud', metadata,*[
    Column('constraint_id', INTEGER(display_width=11), primary_key=False),
    Column('scenario_id', INTEGER(display_width=11), primary_key=False),
    Column('group_id', INTEGER(display_width=11), primary_key=False),
    Column('constant', DOUBLE(asdecimal=True), primary_key=False),
    Column('op', VARCHAR(length=10), primary_key=False),
    Column('action', VARCHAR(length=12), primary_key=False),
    Column('aud_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('aud_time', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),])


tDataset = Table('tDataset', metadata,*[
    Column('dataset_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('data_id', INTEGER(display_width=11), primary_key=False, nullable=False),
    Column('data_type', VARCHAR(length=45), primary_key=False, nullable=False),
    Column('data_units', VARCHAR(length=45), primary_key=False),
    Column('data_dimen', VARCHAR(length=45), primary_key=False),
    Column('data_name', VARCHAR(length=45), primary_key=False, nullable=False),
    Column('data_hash', BIGINT(display_width=20), primary_key=False, nullable=False),
    Column('cr_date', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),
    Column('created_by', INTEGER(display_width=11), primary_key=False),
    Column('locked', VARCHAR(length=1), primary_key=False, nullable=False, default=text(u"'N'")),
    ForeignKeyConstraint(['created_by'], [u'hydradb.tUser.user_id'], name=u'tDataset_ibfk_1'),])
Index('created_by', tDataset.c.created_by, unique=False)


tDatasetGroup = Table('tDatasetGroup', metadata,*[
    Column('group_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('group_name', VARCHAR(length=45), primary_key=False, nullable=False),
    Column('cr_date', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),])
Index('group_name', tDatasetGroup.c.group_name, unique=True)


tDatasetGroupItem = Table('tDatasetGroupItem', metadata,*[
    Column('group_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('dataset_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    ForeignKeyConstraint(['group_id'], [u'hydradb.tDatasetGroup.group_id'], name=u'tDatasetGroupItem_ibfk_1'),
    ForeignKeyConstraint(['dataset_id'], [u'hydradb.tDataset.dataset_id'], name=u'tDatasetGroupItem_ibfk_2'),])
Index('dataset_id', tDatasetGroupItem.c.dataset_id, unique=False)


tDatasetGroupItem_aud = Table('tDatasetGroupItem_aud', metadata,*[
    Column('group_id', INTEGER(display_width=11), primary_key=False),
    Column('dataset_id', INTEGER(display_width=11), primary_key=False),
    Column('action', VARCHAR(length=12), primary_key=False),
    Column('aud_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('aud_time', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),])


tDatasetGroup_aud = Table('tDatasetGroup_aud', metadata,*[
    Column('group_id', INTEGER(display_width=11), primary_key=False),
    Column('group_name', VARCHAR(length=45), primary_key=False),
    Column('cr_date', TIMESTAMP(), primary_key=False),
    Column('action', VARCHAR(length=12), primary_key=False),
    Column('aud_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('aud_time', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),])


tDataset_aud = Table('tDataset_aud', metadata,*[
    Column('dataset_id', INTEGER(display_width=11), primary_key=False),
    Column('data_id', INTEGER(display_width=11), primary_key=False),
    Column('data_type', VARCHAR(length=45), primary_key=False),
    Column('data_units', VARCHAR(length=45), primary_key=False),
    Column('data_dimen', VARCHAR(length=45), primary_key=False),
    Column('data_name', VARCHAR(length=45), primary_key=False),
    Column('data_hash', BIGINT(display_width=20), primary_key=False),
    Column('cr_date', TIMESTAMP(), primary_key=False),
    Column('created_by', INTEGER(display_width=11), primary_key=False),
    Column('locked', VARCHAR(length=1), primary_key=False),
    Column('action', VARCHAR(length=12), primary_key=False),
    Column('aud_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('aud_time', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),])


tDescriptor = Table('tDescriptor', metadata,*[
    Column('data_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('desc_val', VARCHAR(length=1000), primary_key=False, nullable=False),])


tDescriptor_aud = Table('tDescriptor_aud', metadata,*[
    Column('data_id', INTEGER(display_width=11), primary_key=False),
    Column('desc_val', VARCHAR(length=1000), primary_key=False),
    Column('action', VARCHAR(length=12), primary_key=False),
    Column('aud_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('aud_time', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),])


tEqTimeSeries = Table('tEqTimeSeries', metadata,*[
    Column('data_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('start_time', DECIMAL(unsigned=True, precision=30, scale=20), primary_key=False, nullable=False),
    Column('frequency', DOUBLE(asdecimal=True), primary_key=False, nullable=False),
    Column('arr_data', BLOB(), primary_key=False, nullable=False),])


tEqTimeSeries_aud = Table('tEqTimeSeries_aud', metadata,*[
    Column('data_id', INTEGER(display_width=11), primary_key=False),
    Column('start_time', DECIMAL(unsigned=True, precision=30, scale=20), primary_key=False),
    Column('frequency', DOUBLE(asdecimal=True), primary_key=False),
    Column('arr_data', BLOB(), primary_key=False),
    Column('action', VARCHAR(length=12), primary_key=False),
    Column('aud_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('aud_time', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),])


tLink = Table('tLink', metadata,*[
    Column('link_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('network_id', INTEGER(display_width=11), primary_key=False, nullable=False),
    Column('status', VARCHAR(length=1), primary_key=False, nullable=False, default=text(u"'A'")),
    Column('node_1_id', INTEGER(display_width=11), primary_key=False, nullable=False),
    Column('node_2_id', INTEGER(display_width=11), primary_key=False, nullable=False),
    Column('link_name', VARCHAR(length=45), primary_key=False),
    Column('link_description', VARCHAR(length=1000), primary_key=False),
    Column('link_layout', TEXT(), primary_key=False),
    Column('cr_date', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),
    ForeignKeyConstraint(['node_2_id'], [u'hydradb.tNode.node_id'], name=u'tLink_ibfk_3'),
    ForeignKeyConstraint(['network_id'], [u'hydradb.tNetwork.network_id'], name=u'tLink_ibfk_1'),
    ForeignKeyConstraint(['node_1_id'], [u'hydradb.tNode.node_id'], name=u'tLink_ibfk_2'),])
Index('node_1_id', tLink.c.node_1_id, tLink.c.node_2_id, tLink.c.link_id, unique=True)
Index('node_2_id', tLink.c.node_2_id, unique=False)
Index('network_id', tLink.c.network_id, tLink.c.link_name, unique=True)


tLink_aud = Table('tLink_aud', metadata,*[
    Column('link_id', INTEGER(display_width=11), primary_key=False),
    Column('network_id', INTEGER(display_width=11), primary_key=False),
    Column('status', VARCHAR(length=1), primary_key=False),
    Column('node_1_id', INTEGER(display_width=11), primary_key=False),
    Column('node_2_id', INTEGER(display_width=11), primary_key=False),
    Column('link_name', VARCHAR(length=45), primary_key=False),
    Column('link_description', VARCHAR(length=1000), primary_key=False),
    Column('link_layout', TEXT(), primary_key=False),
    Column('cr_date', TIMESTAMP(), primary_key=False),
    Column('action', VARCHAR(length=12), primary_key=False),
    Column('aud_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('aud_time', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),])


tMetadata = Table('tMetadata', metadata,*[
    Column('dataset_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('metadata_name', VARCHAR(length=45), primary_key=True, nullable=False),
    Column('metadata_val', BLOB(), primary_key=False, nullable=False),
    ForeignKeyConstraint(['dataset_id'], [u'hydradb.tDataset.dataset_id'], name=u'tMetadata_ibfk_1'),])


tMetadata_aud = Table('tMetadata_aud', metadata,*[
    Column('dataset_id', INTEGER(display_width=11), primary_key=False),
    Column('metadata_name', VARCHAR(length=45), primary_key=False),
    Column('metadata_val', BLOB(), primary_key=False),
    Column('action', VARCHAR(length=12), primary_key=False),
    Column('aud_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('aud_time', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),])


tNetwork = Table('tNetwork', metadata,*[
    Column('network_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('network_name', VARCHAR(length=45), primary_key=False, nullable=False),
    Column('network_description', VARCHAR(length=1000), primary_key=False),
    Column('network_layout', TEXT(), primary_key=False),
    Column('project_id', INTEGER(display_width=11), primary_key=False, nullable=False),
    Column('status', VARCHAR(length=1), primary_key=False, nullable=False, default=text(u"'A'")),
    Column('cr_date', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),
    Column('projection', VARCHAR(length=1000), primary_key=False),
    Column('created_by', INTEGER(display_width=11), primary_key=False),
    ForeignKeyConstraint(['project_id'], [u'hydradb.tProject.project_id'], name=u'tNetwork_ibfk_2'),
    ForeignKeyConstraint(['created_by'], [u'hydradb.tUser.user_id'], name=u'tNetwork_ibfk_1'),])
Index('created_by', tNetwork.c.created_by, unique=False)
Index('project_id', tNetwork.c.project_id, tNetwork.c.network_name, unique=True)


tNetwork_aud = Table('tNetwork_aud', metadata,*[
    Column('network_id', INTEGER(display_width=11), primary_key=False),
    Column('network_name', VARCHAR(length=45), primary_key=False),
    Column('network_description', VARCHAR(length=1000), primary_key=False),
    Column('network_layout', TEXT(), primary_key=False),
    Column('project_id', INTEGER(display_width=11), primary_key=False),
    Column('status', VARCHAR(length=1), primary_key=False),
    Column('cr_date', TIMESTAMP(), primary_key=False),
    Column('projection', VARCHAR(length=1000), primary_key=False),
    Column('created_by', INTEGER(display_width=11), primary_key=False),
    Column('action', VARCHAR(length=12), primary_key=False),
    Column('aud_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('aud_time', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),])


tNode = Table('tNode', metadata,*[
    Column('node_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('network_id', INTEGER(display_width=11), primary_key=False, nullable=False),
    Column('node_description', VARCHAR(length=1000), primary_key=False),
    Column('node_name', VARCHAR(length=45), primary_key=False, nullable=False),
    Column('status', VARCHAR(length=1), primary_key=False, nullable=False, default=text(u"'A'")),
    Column('node_x', DOUBLE(asdecimal=True), primary_key=False),
    Column('node_y', DOUBLE(asdecimal=True), primary_key=False),
    Column('node_layout', TEXT(), primary_key=False),
    Column('cr_date', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),
    ForeignKeyConstraint(['network_id'], [u'hydradb.tNetwork.network_id'], name=u'tNode_ibfk_1'),])
Index('network_id', tNode.c.network_id, tNode.c.node_name, unique=True)


tNode_aud = Table('tNode_aud', metadata,*[
    Column('node_id', INTEGER(display_width=11), primary_key=False),
    Column('network_id', INTEGER(display_width=11), primary_key=False),
    Column('node_description', VARCHAR(length=1000), primary_key=False),
    Column('node_name', VARCHAR(length=45), primary_key=False),
    Column('status', VARCHAR(length=1), primary_key=False),
    Column('node_x', DOUBLE(asdecimal=True), primary_key=False),
    Column('node_y', DOUBLE(asdecimal=True), primary_key=False),
    Column('node_layout', TEXT(), primary_key=False),
    Column('cr_date', TIMESTAMP(), primary_key=False),
    Column('action', VARCHAR(length=12), primary_key=False),
    Column('aud_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('aud_time', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),])


tOwner = Table('tOwner', metadata,*[
    Column('user_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('ref_key', VARCHAR(length=45), primary_key=True, nullable=False),
    Column('ref_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('cr_date', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),
    Column('view', VARCHAR(length=1), primary_key=False, nullable=False),
    Column('edit', VARCHAR(length=1), primary_key=False, nullable=False),
    Column('share', VARCHAR(length=1), primary_key=False, nullable=False),
    ForeignKeyConstraint(['user_id'], [u'hydradb.tUser.user_id'], name=u'tOwner_ibfk_1'),])
Index('iOwner_1', tOwner.c.ref_key, tOwner.c.ref_id, unique=False)


tOwner_aud = Table('tOwner_aud', metadata,*[
    Column('user_id', INTEGER(display_width=11), primary_key=False),
    Column('ref_key', VARCHAR(length=45), primary_key=False),
    Column('ref_id', INTEGER(display_width=11), primary_key=False),
    Column('cr_date', TIMESTAMP(), primary_key=False),
    Column('view', VARCHAR(length=1), primary_key=False),
    Column('edit', VARCHAR(length=1), primary_key=False),
    Column('share', VARCHAR(length=1), primary_key=False),
    Column('action', VARCHAR(length=12), primary_key=False),
    Column('aud_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('aud_time', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),])


tPerm = Table('tPerm', metadata,*[
    Column('perm_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('perm_code', VARCHAR(length=45), primary_key=False, nullable=False),
    Column('perm_name', VARCHAR(length=45), primary_key=False, nullable=False),
    Column('cr_date', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),])
Index('iPerm1', tPerm.c.perm_code, unique=False)
Index('perm_code', tPerm.c.perm_code, unique=True)
Index('perm_code_2', tPerm.c.perm_code, unique=False)


tPerm_aud = Table('tPerm_aud', metadata,*[
    Column('perm_id', INTEGER(display_width=11), primary_key=False),
    Column('perm_code', VARCHAR(length=45), primary_key=False),
    Column('perm_name', VARCHAR(length=45), primary_key=False),
    Column('cr_date', TIMESTAMP(), primary_key=False),
    Column('action', VARCHAR(length=12), primary_key=False),
    Column('aud_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('aud_time', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),])


tProject = Table('tProject', metadata,*[
    Column('project_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('project_name', VARCHAR(length=45), primary_key=False, nullable=False),
    Column('project_description', VARCHAR(length=1000), primary_key=False),
    Column('status', VARCHAR(length=1), primary_key=False, nullable=False, default=text(u"'A'")),
    Column('cr_date', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),
    Column('created_by', INTEGER(display_width=11), primary_key=False),
    ForeignKeyConstraint(['created_by'], [u'hydradb.tUser.user_id'], name=u'tProject_ibfk_1'),])
Index('project_name', tProject.c.project_name, unique=True)
Index('created_by', tProject.c.created_by, unique=False)


tProject_aud = Table('tProject_aud', metadata,*[
    Column('project_id', INTEGER(display_width=11), primary_key=False),
    Column('project_name', VARCHAR(length=45), primary_key=False),
    Column('project_description', VARCHAR(length=1000), primary_key=False),
    Column('status', VARCHAR(length=1), primary_key=False),
    Column('cr_date', TIMESTAMP(), primary_key=False),
    Column('created_by', INTEGER(display_width=11), primary_key=False),
    Column('action', VARCHAR(length=12), primary_key=False),
    Column('aud_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('aud_time', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),])


tResourceAttr = Table('tResourceAttr', metadata,*[
    Column('resource_attr_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('attr_id', INTEGER(display_width=11), primary_key=False, nullable=False),
    Column('ref_key', VARCHAR(length=45), primary_key=False, nullable=False),
    Column('ref_id', INTEGER(display_width=11), primary_key=False, nullable=False),
    Column('attr_is_var', VARCHAR(length=1), primary_key=False, nullable=False, default=text(u"'N'")),
    ForeignKeyConstraint(['attr_id'], [u'hydradb.tAttr.attr_id'], name=u'tResourceAttr_ibfk_1'),])
Index('iResourceAttr_1', tResourceAttr.c.attr_id, tResourceAttr.c.ref_key, tResourceAttr.c.ref_id, unique=True)
Index('iResourceAttr_2', tResourceAttr.c.ref_key, tResourceAttr.c.ref_id, unique=False)


tResourceAttr_aud = Table('tResourceAttr_aud', metadata,*[
    Column('resource_attr_id', INTEGER(display_width=11), primary_key=False),
    Column('attr_id', INTEGER(display_width=11), primary_key=False),
    Column('ref_key', VARCHAR(length=45), primary_key=False),
    Column('ref_id', INTEGER(display_width=11), primary_key=False),
    Column('attr_is_var', VARCHAR(length=1), primary_key=False),
    Column('action', VARCHAR(length=12), primary_key=False),
    Column('aud_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('aud_time', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),])


tResourceGroup = Table('tResourceGroup', metadata,*[
    Column('group_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('group_name', VARCHAR(length=45), primary_key=False, nullable=False),
    Column('group_description', VARCHAR(length=1000), primary_key=False),
    Column('status', VARCHAR(length=1), primary_key=False),
    Column('cr_date', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),
    Column('network_id', INTEGER(display_width=11), primary_key=False, nullable=False),
    ForeignKeyConstraint(['network_id'], [u'hydradb.tNetwork.network_id'], name=u'tResourceGroup_ibfk_1'),])
Index('network_id', tResourceGroup.c.network_id, unique=False)


tResourceGroupItem = Table('tResourceGroupItem', metadata,*[
    Column('item_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('ref_id', INTEGER(display_width=11), primary_key=False, nullable=False),
    Column('ref_key', VARCHAR(length=45), primary_key=False, nullable=False),
    Column('group_id', INTEGER(display_width=11), primary_key=False, nullable=False),
    Column('scenario_id', INTEGER(display_width=11), primary_key=False, nullable=False),
    ForeignKeyConstraint(['group_id'], [u'hydradb.tResourceGroup.group_id'], name=u'tResourceGroupItem_ibfk_1'),
    ForeignKeyConstraint(['scenario_id'], [u'hydradb.tScenario.scenario_id'], name=u'tResourceGroupItem_ibfk_2'),])
Index('group_id', tResourceGroupItem.c.group_id, unique=False)
Index('scenario_id', tResourceGroupItem.c.scenario_id, tResourceGroupItem.c.group_id, tResourceGroupItem.c.ref_key, tResourceGroupItem.c.ref_id, unique=True)


tResourceGroupItem_aud = Table('tResourceGroupItem_aud', metadata,*[
    Column('item_id', INTEGER(display_width=11), primary_key=False),
    Column('ref_id', INTEGER(display_width=11), primary_key=False),
    Column('ref_key', VARCHAR(length=45), primary_key=False),
    Column('group_id', INTEGER(display_width=11), primary_key=False),
    Column('scenario_id', INTEGER(display_width=11), primary_key=False),
    Column('action', VARCHAR(length=12), primary_key=False),
    Column('aud_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('aud_time', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),])


tResourceGroup_aud = Table('tResourceGroup_aud', metadata,*[
    Column('group_id', INTEGER(display_width=11), primary_key=False),
    Column('group_name', VARCHAR(length=45), primary_key=False),
    Column('group_description', VARCHAR(length=1000), primary_key=False),
    Column('status', VARCHAR(length=1), primary_key=False),
    Column('cr_date', TIMESTAMP(), primary_key=False),
    Column('network_id', INTEGER(display_width=11), primary_key=False),
    Column('action', VARCHAR(length=12), primary_key=False),
    Column('aud_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('aud_time', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),])


tResourceScenario = Table('tResourceScenario', metadata,*[
    Column('dataset_id', INTEGER(display_width=11), primary_key=False, nullable=False),
    Column('scenario_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('resource_attr_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    ForeignKeyConstraint(['scenario_id'], [u'hydradb.tScenario.scenario_id'], name=u'tResourceScenario_ibfk_1'),
    ForeignKeyConstraint(['resource_attr_id'], [u'hydradb.tResourceAttr.resource_attr_id'], name=u'tResourceScenario_ibfk_3'),
    ForeignKeyConstraint(['dataset_id'], [u'hydradb.tDataset.dataset_id'], name=u'tResourceScenario_ibfk_2'),])
Index('scenario_id', tResourceScenario.c.scenario_id, unique=False)
Index('dataset_id', tResourceScenario.c.dataset_id, unique=False)


tResourceScenario_aud = Table('tResourceScenario_aud', metadata,*[
    Column('dataset_id', INTEGER(display_width=11), primary_key=False),
    Column('scenario_id', INTEGER(display_width=11), primary_key=False),
    Column('resource_attr_id', INTEGER(display_width=11), primary_key=False),
    Column('action', VARCHAR(length=12), primary_key=False),
    Column('aud_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('aud_time', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),])


tResourceType = Table('tResourceType', metadata,*[
    Column('ref_key', VARCHAR(length=45), primary_key=True, nullable=False),
    Column('ref_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('type_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    ForeignKeyConstraint(['type_id'], [u'hydradb.tTemplateType.type_id'], name=u'tResourceType_ibfk_1'),])
Index('type_id', tResourceType.c.type_id, unique=False)


tResourceType_aud = Table('tResourceType_aud', metadata,*[
    Column('ref_key', VARCHAR(length=45), primary_key=False),
    Column('ref_id', INTEGER(display_width=11), primary_key=False),
    Column('type_id', INTEGER(display_width=11), primary_key=False),
    Column('action', VARCHAR(length=12), primary_key=False),
    Column('aud_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('aud_time', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),])


tRole = Table('tRole', metadata,*[
    Column('role_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('role_code', VARCHAR(length=45), primary_key=False, nullable=False),
    Column('role_name', VARCHAR(length=45), primary_key=False, nullable=False),
    Column('cr_date', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),])
Index('role_code', tRole.c.role_code, unique=True)
Index('iRole1', tRole.c.role_code, unique=False)


tRolePerm = Table('tRolePerm', metadata,*[
    Column('perm_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('role_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('cr_date', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),
    ForeignKeyConstraint(['role_id'], [u'hydradb.tRole.role_id'], name=u'tRolePerm_ibfk_2'),
    ForeignKeyConstraint(['perm_id'], [u'hydradb.tPerm.perm_id'], name=u'tRolePerm_ibfk_1'),])
Index('role_id', tRolePerm.c.role_id, unique=False)


tRolePerm_aud = Table('tRolePerm_aud', metadata,*[
    Column('perm_id', INTEGER(display_width=11), primary_key=False),
    Column('role_id', INTEGER(display_width=11), primary_key=False),
    Column('cr_date', TIMESTAMP(), primary_key=False),
    Column('action', VARCHAR(length=12), primary_key=False),
    Column('aud_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('aud_time', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),])


tRoleUser = Table('tRoleUser', metadata,*[
    Column('user_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('role_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('cr_date', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),
    ForeignKeyConstraint(['role_id'], [u'hydradb.tRole.role_id'], name=u'tRoleUser_ibfk_2'),
    ForeignKeyConstraint(['user_id'], [u'hydradb.tUser.user_id'], name=u'tRoleUser_ibfk_1'),])
Index('role_id', tRoleUser.c.role_id, unique=False)


tRoleUser_aud = Table('tRoleUser_aud', metadata,*[
    Column('user_id', INTEGER(display_width=11), primary_key=False),
    Column('role_id', INTEGER(display_width=11), primary_key=False),
    Column('cr_date', TIMESTAMP(), primary_key=False),
    Column('action', VARCHAR(length=12), primary_key=False),
    Column('aud_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('aud_time', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),])


tRole_aud = Table('tRole_aud', metadata,*[
    Column('role_id', INTEGER(display_width=11), primary_key=False),
    Column('role_code', VARCHAR(length=45), primary_key=False),
    Column('role_name', VARCHAR(length=45), primary_key=False),
    Column('cr_date', TIMESTAMP(), primary_key=False),
    Column('action', VARCHAR(length=12), primary_key=False),
    Column('aud_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('aud_time', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),])


tScalar = Table('tScalar', metadata,*[
    Column('data_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('param_value', DOUBLE(asdecimal=True), primary_key=False, nullable=False),])


tScalar_aud = Table('tScalar_aud', metadata,*[
    Column('data_id', INTEGER(display_width=11), primary_key=False),
    Column('param_value', DOUBLE(asdecimal=True), primary_key=False),
    Column('action', VARCHAR(length=12), primary_key=False),
    Column('aud_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('aud_time', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),])


tScenario = Table('tScenario', metadata,*[
    Column('scenario_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('scenario_name', VARCHAR(length=45), primary_key=False, nullable=False),
    Column('scenario_description', VARCHAR(length=1000), primary_key=False),
    Column('status', VARCHAR(length=1), primary_key=False, nullable=False, default=text(u"'A'")),
    Column('network_id', INTEGER(display_width=11), primary_key=False),
    Column('start_time', DECIMAL(unsigned=True, precision=30, scale=20), primary_key=False),
    Column('end_time', DECIMAL(unsigned=True, precision=30, scale=20), primary_key=False),
    Column('time_step', VARCHAR(length=60), primary_key=False),
    Column('cr_date', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),
    ForeignKeyConstraint(['network_id'], [u'hydradb.tNetwork.network_id'], name=u'tScenario_ibfk_1'),])
Index('network_id', tScenario.c.network_id, tScenario.c.scenario_name, unique=True)


tScenario_aud = Table('tScenario_aud', metadata,*[
    Column('scenario_id', INTEGER(display_width=11), primary_key=False),
    Column('scenario_name', VARCHAR(length=45), primary_key=False),
    Column('scenario_description', VARCHAR(length=1000), primary_key=False),
    Column('status', VARCHAR(length=1), primary_key=False),
    Column('network_id', INTEGER(display_width=11), primary_key=False),
    Column('start_time', DECIMAL(unsigned=True, precision=30, scale=20), primary_key=False),
    Column('end_time', DECIMAL(unsigned=True, precision=30, scale=20), primary_key=False),
    Column('time_step', VARCHAR(length=60), primary_key=False),
    Column('cr_date', TIMESTAMP(), primary_key=False),
    Column('action', VARCHAR(length=12), primary_key=False),
    Column('aud_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('aud_time', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),])


tTemplate = Table('tTemplate', metadata,*[
    Column('template_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('template_name', VARCHAR(length=45), primary_key=False, nullable=False),
    Column('layout', TEXT(), primary_key=False),])
Index('template_name', tTemplate.c.template_name, unique=True)


tTemplateType = Table('tTemplateType', metadata,*[
    Column('type_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('type_name', VARCHAR(length=45), primary_key=False, nullable=False),
    Column('template_id', INTEGER(display_width=11), primary_key=False),
    Column('alias', VARCHAR(length=45), primary_key=False),
    Column('layout', TEXT(), primary_key=False),
    ForeignKeyConstraint(['template_id'], [u'hydradb.tTemplate.template_id'], name=u'tTemplateType_ibfk_1'),])
Index('template_id', tTemplateType.c.template_id, tTemplateType.c.type_name, unique=True)


tTemplateType_aud = Table('tTemplateType_aud', metadata,*[
    Column('type_id', INTEGER(display_width=11), primary_key=False),
    Column('type_name', VARCHAR(length=45), primary_key=False),
    Column('template_id', INTEGER(display_width=11), primary_key=False),
    Column('alias', VARCHAR(length=45), primary_key=False),
    Column('layout', TEXT(), primary_key=False),
    Column('action', VARCHAR(length=12), primary_key=False),
    Column('aud_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('aud_time', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),])


tTemplate_aud = Table('tTemplate_aud', metadata,*[
    Column('template_id', INTEGER(display_width=11), primary_key=False),
    Column('template_name', VARCHAR(length=45), primary_key=False),
    Column('layout', TEXT(), primary_key=False),
    Column('action', VARCHAR(length=12), primary_key=False),
    Column('aud_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('aud_time', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),])


tTimeSeries = Table('tTimeSeries', metadata,*[
    Column('data_id', INTEGER(display_width=11), primary_key=True, nullable=False),])


tTimeSeriesData = Table('tTimeSeriesData', metadata,*[
    Column('data_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('ts_time', DECIMAL(unsigned=True, precision=30, scale=20), primary_key=True, nullable=False),
    Column('ts_value', BLOB(), primary_key=False, nullable=False),
    ForeignKeyConstraint(['data_id'], [u'hydradb.tTimeSeries.data_id'], name=u'tTimeSeriesData_ibfk_1'),])


tTimeSeriesData_aud = Table('tTimeSeriesData_aud', metadata,*[
    Column('data_id', INTEGER(display_width=11), primary_key=False),
    Column('ts_time', DECIMAL(unsigned=True, precision=30, scale=20), primary_key=False),
    Column('ts_value', BLOB(), primary_key=False),
    Column('action', VARCHAR(length=12), primary_key=False),
    Column('aud_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('aud_time', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),])


tTimeSeries_aud = Table('tTimeSeries_aud', metadata,*[
    Column('data_id', INTEGER(display_width=11), primary_key=False),
    Column('action', VARCHAR(length=12), primary_key=False),
    Column('aud_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('aud_time', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),])


tTypeAttr = Table('tTypeAttr', metadata,*[
    Column('attr_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('type_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('default_dataset_id', INTEGER(display_width=11), primary_key=False),
    Column('attr_is_var', VARCHAR(length=1), primary_key=False, default=text(u"'N'")),
    Column('data_type', VARCHAR(length=45), primary_key=False),
    Column('dimension', VARCHAR(length=45), primary_key=False),
    ForeignKeyConstraint(['type_id'], [u'hydradb.tTemplateType.type_id'], name=u'tTypeAttr_ibfk_2'),
    ForeignKeyConstraint(['default_dataset_id'], [u'hydradb.tDataset.dataset_id'], name=u'tTypeAttr_ibfk_3'),
    ForeignKeyConstraint(['attr_id'], [u'hydradb.tAttr.attr_id'], name=u'tTypeAttr_ibfk_1'),])
Index('type_id', tTypeAttr.c.type_id, unique=False)
Index('default_dataset_id', tTypeAttr.c.default_dataset_id, unique=False)


tTypeAttr_aud = Table('tTypeAttr_aud', metadata,*[
    Column('attr_id', INTEGER(display_width=11), primary_key=False),
    Column('type_id', INTEGER(display_width=11), primary_key=False),
    Column('default_dataset_id', INTEGER(display_width=11), primary_key=False),
    Column('attr_is_var', VARCHAR(length=1), primary_key=False),
    Column('data_type', VARCHAR(length=45), primary_key=False),
    Column('dimension', VARCHAR(length=45), primary_key=False),
    Column('action', VARCHAR(length=12), primary_key=False),
    Column('aud_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('aud_time', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),])


tUser = Table('tUser', metadata,*[
    Column('user_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('username', VARCHAR(length=45), primary_key=False, nullable=False),
    Column('password', VARCHAR(length=1000), primary_key=False, nullable=False),
    Column('display_name', VARCHAR(length=60), primary_key=False, nullable=False, default=text(u"''")),
    Column('last_login', DATETIME(), primary_key=False),
    Column('last_edit', DATETIME(), primary_key=False),
    Column('cr_date', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),])
Index('iUser', tUser.c.username, unique=False)


tUser_aud = Table('tUser_aud', metadata,*[
    Column('user_id', INTEGER(display_width=11), primary_key=False),
    Column('username', VARCHAR(length=45), primary_key=False),
    Column('password', VARCHAR(length=1000), primary_key=False),
    Column('display_name', VARCHAR(length=60), primary_key=False),
    Column('last_login', DATETIME(), primary_key=False),
    Column('last_edit', DATETIME(), primary_key=False),
    Column('cr_date', TIMESTAMP(), primary_key=False),
    Column('action', VARCHAR(length=12), primary_key=False),
    Column('aud_id', INTEGER(display_width=11), primary_key=True, nullable=False),
    Column('aud_time', TIMESTAMP(), primary_key=False, nullable=False, default=text(u'CURRENT_TIMESTAMP')),])

